### ISSUE TITLE
Mettre un recherche custom

### ISSUE THREAD

**Issue by gaetan1903** [iTeam-S/WebSearch#10]
mettre une fonction custom qui peut prendre deux paramètre, l'extension voulu et la vérification de ce dernier.

Pour éviter de mettre en fonction tous les types de fichiers possibles

**Comment by rootkit7628** [comment]
I've added the custom search here [#259cd6f](https://github.com/iTeam-S/WebSearch/pull/11/commits/259cd6f2d35808eb9a8fa028fe2488da812b3eb6)
